<a href="https://colab.research.google.com/github/rushikesh-aware/machine-learn/blob/master/pandasassigment1_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
#import required libraries
import numpy as np
import pandas as pd

Import pandas as pd
Import numpy as np

In [9]:
#load  data from imdb_1000.csv into dataframe and display it
from google.colab import files
uploaded = files.upload()
df = pd.read_csv("imdb_1000.csv")
df

Saving imdb_1000.csv to imdb_1000 (1).csv

     star_rating  ...                                        actors_list
0            9.3  ...  [u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt...
1            9.2  ...    [u'Marlon Brando', u'Al Pacino', u'James Caan']
2            9.1  ...  [u'Al Pacino', u'Robert De Niro', u'Robert Duv...
3            9.0  ...  [u'Christian Bale', u'Heath Ledger', u'Aaron E...
4            8.9  ...  [u'John Travolta', u'Uma Thurman', u'Samuel L....
..           ...  ...                                                ...
974          7.4  ...  [u'Dustin Hoffman', u'Jessica Lange', u'Teri G...
975          7.4  ...  [u'Michael J. Fox', u'Christopher Lloyd', u'Ma...
976          7.4  ...  [u'Russell Crowe', u'Paul Bettany', u'Billy Bo...
977          7.4  ...  [u'JoBeth Williams', u"Heather O'Rourke", u'Cr...
978          7.4  ...  [u'Charlie Sheen', u'Michael Douglas', u'Tamar...

[979 rows x 6 columns]

In [10]:
#display info about dataframe
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 979 entries, 0 to 978
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   star_rating     979 non-null    float64
 1   title           979 non-null    object
 2   content_rating  976 non-null    object
 3   genre           979 non-null    object
 4   duration        979 non-null    int64
 5   actors_list     979 non-null    object
dtypes: float64(1), int64(1), object(4)
memory usage: 46.0+ KB

In [11]:
#describe dataframe
df.describe()

       star_rating    duration
count   979.000000  979.000000
mean      7.889785  120.979571
std       0.336069   26.218010
min       7.400000   64.000000
25%       7.600000  102.000000
50%       7.800000  117.000000
75%       8.100000  134.000000
max       9.300000  242.000000

In [12]:
#display first 10 rows from dataframe
firstten = df.head(10)
firstten

   star_rating  ...                                        actors_list
0          9.3  ...  [u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt...
1          9.2  ...    [u'Marlon Brando', u'Al Pacino', u'James Caan']
2          9.1  ...  [u'Al Pacino', u'Robert De Niro', u'Robert Duv...
3          9.0  ...  [u'Christian Bale', u'Heath Ledger', u'Aaron E...
4          8.9  ...  [u'John Travolta', u'Uma Thurman', u'Samuel L....
5          8.9  ...  [u'Henry Fonda', u'Lee J. Cobb', u'Martin Bals...
6          8.9  ...  [u'Clint Eastwood', u'Eli Wallach', u'Lee Van ...
7          8.9  ...  [u'Elijah Wood', u'Viggo Mortensen', u'Ian McK...
8          8.9  ...  [u'Liam Neeson', u'Ralph Fiennes', u'Ben Kings...
9          8.9  ...  [u'Brad Pitt', u'Edward Norton', u'Helena Bonh...

[10 rows x 6 columns]

In [13]:
#display last 10 rows from dataframe object
lastten = df.tail(10)
lastten

     star_rating  ...                                        actors_list
969          7.4  ...  [u'Gerard Butler', u'Jamie Foxx', u'Leslie Bibb']
970          7.4  ...  [u'Michael Douglas', u'Tobey Maguire', u'Franc...
971          7.4  ...  [u'Matthew Macfadyen', u'Peter Dinklage', u'Ew...
972          7.4  ...  [u'Ryan Gosling', u'Michelle Williams', u'John...
973          7.4  ...  [u'Tobey Maguire', u'Charlize Theron', u'Micha...
974          7.4  ...  [u'Dustin Hoffman', u'Jessica Lange', u'Teri G...
975          7.4  ...  [u'Michael J. Fox', u'Christopher Lloyd', u'Ma...
976          7.4  ...  [u'Russell Crowe', u'Paul Bettany', u'Billy Bo...
977          7.4  ...  [u'JoBeth Williams', u"Heather O'Rourke", u'Cr...
978          7.4  ...  [u'Charlie Sheen', u'Michael Douglas', u'Tamar...

[10 rows x 6 columns]

In [14]:
# display rows from 100 index to 200 only
a = df[100:200]
a

     star_rating  ...                                        actors_list
100          8.3  ...  [u'Humphrey Bogart', u'Walter Huston', u'Tim H...
101          8.3  ...  [u'Graham Chapman', u'John Cleese', u'Eric Idle']
102          8.3  ...  [u'Matthew Modine', u'R. Lee Ermey', u"Vincent...
103          8.3  ...  [u'Jack Lemmon', u'Shirley MacLaine', u'Fred M...
104          8.3  ...  [u'Takashi Shimura', u'Nobuo Kaneko', u"Shin'i...
..           ...  ...                                                ...
195          8.1  ...  [u'Charlie Sheen', u'Tom Berenger', u'Willem D...
196          8.1  ...  [u'Chris Pratt', u'Vin Diesel', u'Bradley Coop...
197          8.1  ...  [u'Daniel Day-Lewis', u'Pete Postlethwaite', u...
198          8.1  ...  [u'Uma Thurman', u'David Carradine', u'Daryl H...
199          8.1  ...  [u'Tommy Lee Jones', u'Javier Bardem', u'Josh ...

[100 rows x 6 columns]

In [30]:
# change bydefauly index to title(title as row labels)
df=df.set_index("title")
df

                                                 star_rating  ...                                        actors_list
title                                                         ...
The Shawshank Redemption                                 9.3  ...  [u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt...
The Godfather                                            9.2  ...    [u'Marlon Brando', u'Al Pacino', u'James Caan']
The Godfather: Part II                                   9.1  ...  [u'Al Pacino', u'Robert De Niro', u'Robert Duv...
The Dark Knight                                          9.0  ...  [u'Christian Bale', u'Heath Ledger', u'Aaron E...
Pulp Fiction                                             8.9  ...  [u'John Travolta', u'Uma Thurman', u'Samuel L....
...                                                      ...  ...                                                ...
Tootsie                                                  7.4  ...  [u'Dustin Hoffman', u'Jessica Lange', u'Teri G...
Back to the Future Part III                              7.4  ...  [u'Michael J. Fox', u'Christopher Lloyd', u'Ma...
Master and Commander: The Far Side of the World          7.4  ...  [u'Russell Crowe', u'Paul Bettany', u'Billy Bo...
Poltergeist                                              7.4  ...  [u'JoBeth Williams', u"Heather O'Rourke", u'Cr...
Wall Street                                              7.4  ...  [u'Charlie Sheen', u'Michael Douglas', u'Tamar...

[979 rows x 5 columns]

In [31]:
#display rows from label 'The Dark Knight' to 'X-Men' by using loc
df.loc['The Dark Knight' : 'X-Men']

                                               star_rating  ...                                        actors_list
title                                                       ...
The Dark Knight                                        9.0  ...  [u'Christian Bale', u'Heath Ledger', u'Aaron E...
Pulp Fiction                                           8.9  ...  [u'John Travolta', u'Uma Thurman', u'Samuel L....
12 Angry Men                                           8.9  ...  [u'Henry Fonda', u'Lee J. Cobb', u'Martin Bals...
The Good, the Bad and the Ugly                         8.9  ...  [u'Clint Eastwood', u'Eli Wallach', u'Lee Van ...
The Lord of the Rings: The Return of the King          8.9  ...  [u'Elijah Wood', u'Viggo Mortensen', u'Ian McK...
...                                                    ...  ...                                                ...
Bound                                                  7.4  ...  [u'Jennifer Tilly', u'Gina Gershon', u'Joe Pan...
Sleepy Hollow                                          7.4  ...  [u'Johnny Depp', u'Christina Ricci', u'Miranda...
Pirate Radio                                           7.4  ...  [u'Philip Seymour Hoffman', u'Bill Nighy', u'N...
The NeverEnding Story                                  7.4  ...  [u'Noah Hathaway', u'Barret Oliver', u'Tami St...
X-Men                                                  7.4  ...  [u'Patrick Stewart', u'Hugh Jackman', u'Ian Mc...

[952 rows x 5 columns]

In [32]:
#display all rows with star_rating greater than 7
d=df["star_rating"]>7
df[d]

                                                 star_rating  ...                                        actors_list
title                                                         ...
The Shawshank Redemption                                 9.3  ...  [u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt...
The Godfather                                            9.2  ...    [u'Marlon Brando', u'Al Pacino', u'James Caan']
The Godfather: Part II                                   9.1  ...  [u'Al Pacino', u'Robert De Niro', u'Robert Duv...
The Dark Knight                                          9.0  ...  [u'Christian Bale', u'Heath Ledger', u'Aaron E...
Pulp Fiction                                             8.9  ...  [u'John Travolta', u'Uma Thurman', u'Samuel L....
...                                                      ...  ...                                                ...
Tootsie                                                  7.4  ...  [u'Dustin Hoffman', u'Jessica Lange', u'Teri G...
Back to the Future Part III                              7.4  ...  [u'Michael J. Fox', u'Christopher Lloyd', u'Ma...
Master and Commander: The Far Side of the World          7.4  ...  [u'Russell Crowe', u'Paul Bettany', u'Billy Bo...
Poltergeist                                              7.4  ...  [u'JoBeth Williams', u"Heather O'Rourke", u'Cr...
Wall Street                                              7.4  ...  [u'Charlie Sheen', u'Michael Douglas', u'Tamar...

[979 rows x 5 columns]

In [34]:
#display all rows with star_rating greater than 7 and less than 9
d=df["star_rating"]>7
f=df["star_rating"]<9
df[d&f]

                                                 star_rating  ...                                        actors_list
title                                                         ...
Pulp Fiction                                             8.9  ...  [u'John Travolta', u'Uma Thurman', u'Samuel L....
12 Angry Men                                             8.9  ...  [u'Henry Fonda', u'Lee J. Cobb', u'Martin Bals...
The Good, the Bad and the Ugly                           8.9  ...  [u'Clint Eastwood', u'Eli Wallach', u'Lee Van ...
The Lord of the Rings: The Return of the King            8.9  ...  [u'Elijah Wood', u'Viggo Mortensen', u'Ian McK...
Schindler's List                                         8.9  ...  [u'Liam Neeson', u'Ralph Fiennes', u'Ben Kings...
...                                                      ...  ...                                                ...
Tootsie                                                  7.4  ...  [u'Dustin Hoffman', u'Jessica Lange', u'Teri G...
Back to the Future Part III                              7.4  ...  [u'Michael J. Fox', u'Christopher Lloyd', u'Ma...
Master and Commander: The Far Side of the World          7.4  ...  [u'Russell Crowe', u'Paul Bettany', u'Billy Bo...
Poltergeist                                              7.4  ...  [u'JoBeth Williams', u"Heather O'Rourke", u'Cr...
Wall Street                                              7.4  ...  [u'Charlie Sheen', u'Michael Douglas', u'Tamar...

[975 rows x 5 columns]

In [35]:
#display all rows with genre==Crime
c=df["genre"]=="Crime"
df[c]

                          star_rating  ...                                        actors_list
title                                  ...
The Shawshank Redemption          9.3  ...  [u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt...
The Godfather                     9.2  ...    [u'Marlon Brando', u'Al Pacino', u'James Caan']
The Godfather: Part II            9.1  ...  [u'Al Pacino', u'Robert De Niro', u'Robert Duv...
Pulp Fiction                      8.9  ...  [u'John Travolta', u'Uma Thurman', u'Samuel L....
City of God                       8.7  ...  [u'Alexandre Rodrigues', u'Matheus Nachtergael...
...                               ...  ...                                                ...
Brick                             7.5  ...  [u'Joseph Gordon-Levitt', u'Lukas Haas', u'Emi...
Mean Streets                      7.4  ...  [u'Robert De Niro', u'Harvey Keitel', u'David ...
Bound                             7.4  ...  [u'Jennifer Tilly', u'Gina Gershon', u'Joe Pan...
Law Abiding Citizen               7.4  ...  [u'Gerard Butler', u'Jamie Foxx', u'Leslie Bibb']
Wall Street                       7.4  ...  [u'Charlie Sheen', u'Michael Douglas', u'Tamar...

[124 rows x 5 columns]

In [36]:
#count all rows with genre==Crime
df[df.genre=="Crime"].shape[0]

124

In [37]:
#select all rows with duration >100
p=df["duration"]>100
df[p]

                                                 star_rating  ...                                        actors_list
title                                                         ...
The Shawshank Redemption                                 9.3  ...  [u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt...
The Godfather                                            9.2  ...    [u'Marlon Brando', u'Al Pacino', u'James Caan']
The Godfather: Part II                                   9.1  ...  [u'Al Pacino', u'Robert De Niro', u'Robert Duv...
The Dark Knight                                          9.0  ...  [u'Christian Bale', u'Heath Ledger', u'Aaron E...
Pulp Fiction                                             8.9  ...  [u'John Travolta', u'Uma Thurman', u'Samuel L....
...                                                      ...  ...                                                ...
Tootsie                                                  7.4  ...  [u'Dustin Hoffman', u'Jessica Lange', u'Teri G...
Back to the Future Part III                              7.4  ...  [u'Michael J. Fox', u'Christopher Lloyd', u'Ma...
Master and Commander: The Far Side of the World          7.4  ...  [u'Russell Crowe', u'Paul Bettany', u'Billy Bo...
Poltergeist                                              7.4  ...  [u'JoBeth Williams', u"Heather O'Rourke", u'Cr...
Wall Street                                              7.4  ...  [u'Charlie Sheen', u'Michael Douglas', u'Tamar...

[769 rows x 5 columns]